"""
Director class-code map read from each class's own GetClassCode() (vtable slot 12, offset 0x30),
which the save routine calls to write the object directory. Writes docs/director_class_codes.txt.
Usage: python tools/class_codes.py
"""
import pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from dre import vtables, vfuncs, dis

GET_CLASS_CODE_SLOT = 12


def const_return(va):
    """Value returned by a 'mov eax, imm; ret' (or 'xor eax,eax; ret') function, else None."""
    ins = dis(va, 3)
    if len(ins) >= 2 and ins[0].mnemonic == 'mov' and ins[0].op_str.startswith('eax, ') and ins[1].mnemonic == 'ret':
        try:
            return int(ins[0].op_str[5:], 0)
        except ValueError:
            return None
    return None


codes = {}
for name, vts in vtables().items():
    fs = vfuncs(vts[0])
    if len(fs) <= GET_CLASS_CODE_SLOT or not (name.startswith('CPhys') or name.startswith('CDocument')):
        continue
    c = const_return(fs[GET_CLASS_CODE_SLOT])
    if c is not None:
        codes.setdefault(c, []).append(name)

doc = pathlib.Path(__file__).resolve().parent.parent / 'docs' / 'director_class_codes.txt'
rows = ['0x%03x  %s' % (c, ', '.join(sorted(n))) for c, n in sorted(codes.items())]
doc.write_text('# Director 8.9.D2: file class code -> C++ class, from each class\'s GetClassCode() (vtable +0x30).\n'
               '# generated by tools/class_codes.py\n' + '\n'.join(rows) + '\n')
print('\n'.join(rows))
print(len(codes), 'codes')
