"""
Build Director's class-code -> C++ class map from the decompiled object factory (FUN_00cde850).
Handles direct `switch(param_1)` cases and byte-table switches `switch(*(undefined1 *)(param_1 + BASE))`.
Usage: python tools/factory_map.py <factory.c>   -> prints the map, writes docs/director_class_codes.txt
"""
import re, sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from dre import va2off, d

lines = pathlib.Path(sys.argv[1]).read_text(encoding='utf-8').split('\n')

# Pass 1: collect switch contexts with their cases -> first vftable class.
ctx_stack = []          # list of dicts: {'kind': 'direct'|'table', 'base': int, 'depth': brace depth, 'lo','hi'}
cases = []              # (ctx, case_value, class)
pending = []            # case labels waiting for a vftable
depth = 0
guard = None            # (lo, hi) from "if (HI < param_1 - LO) goto default" before a table switch
last_cls = None
for l in lines:
    s = l.strip()
    m = re.match(r'if \((0x[0-9a-f]+|\d+) < param_1 - (0x[0-9a-f]+)U?\) goto', s)
    if m:
        guard = (int(m.group(2), 16), int(m.group(1), 0))
    m = re.match(r'switch\(param_1\) \{', s)
    if m:
        ctx_stack.append({'kind': 'direct', 'depth': depth})
    m = re.match(r'switch\(\*\(undefined1 \*\)\(param_1 \+ (0x[0-9a-f]+)\)\) \{', s)
    if m:
        ctx_stack.append({'kind': 'table', 'base': int(m.group(1), 16), 'depth': depth, 'guard': guard})
    m = re.match(r'case (0x[0-9a-f]+|\d+):', s)
    if m and ctx_stack:
        pending.append((ctx_stack[-1], int(m.group(1), 0)))
    # The object's own vtable pointer is written through *local_NN (inlined constructors write the
    # base class vtable first, then the derived one), so keep the last one before the case ends.
    m = re.search(r'^\*(local_\w+|\(\w+ \*+\)local_\w+) = \(?\w*\s?\**\)?(\w+)::vftable;', s)
    if m and pending:
        last_cls = m.group(2)
    if (s.startswith('goto') or s.startswith('break')) and pending:
        for c, v in pending:
            cases.append((c, v, last_cls))
        pending = []
        last_cls = None
    if re.match(r'case (0x[0-9a-f]+|\d+):', s) and len(pending) == 1:
        last_cls = None
    depth += l.count('{') - l.count('}')
    while ctx_stack and depth <= ctx_stack[-1]['depth']:
        ctx_stack.pop()

# Pass 2: expand table switches.
out = {}
for c, v, cls in cases:
    if c['kind'] == 'direct':
        if cls:
            out.setdefault(v, cls)
    else:
        base = c['base']
        lo, span = c['guard'] if c['guard'] else (0, 0)
        for code in range(lo, lo + span + 1):
            o = va2off(base + code)
            if o is not None and d[o] == v and cls:
                out.setdefault(code, cls)

doc = pathlib.Path(__file__).resolve().parent.parent / 'docs' / 'director_class_codes.txt'
rows = ['0x%03x  %s' % (k, out[k]) for k in sorted(out)]
doc.write_text('# Director 8.9.D2 object factory FUN_00cde850: file class code -> C++ class\n'
               '# generated by tools/factory_map.py from the Ghidra decompile\n' + '\n'.join(rows) + '\n')
print('\n'.join(rows))
print(len(out), 'codes')
