"""Write tools/ghidra/serialize_list.txt: Director's per-class Serialize (vtable slot 25) and top-level save/load.
Usage: python tools/make_serialize_list.py"""
import pathlib, sys
sys.path.insert(0, str(pathlib.Path(__file__).parent))
from dre import vtables, vfuncs

SERIALIZE_SLOT = 25   # vtable offset 0x64, called once per collection by the save routine
TOP = [
    ('_Save_document', 0xce5af0),       # writes header, schema 0x580, version, object directory, collections
    ('_Load_document', 0xcdc5a0),       # checks header/version, calls the body loader, expects 'ENDE'
    ('_Load_body', 0xcd32c0),
]

out = pathlib.Path(__file__).parent / 'ghidra' / 'serialize_list.txt'
seen = {}
lines = ['# name VA  (generated by tools/make_serialize_list.py)']
lines += ['%s 0x%x' % t for t in TOP]
vt = vtables()
for name in sorted(vt):
    if not name.startswith('CPhys'):
        continue
    fs = vfuncs(vt[name][0])
    if len(fs) <= SERIALIZE_SLOT:
        continue
    f = fs[SERIALIZE_SLOT]
    if f in seen:
        lines.append('# %s inherits Serialize from %s' % (name, seen[f]))
        continue
    seen[f] = name
    lines.append('%s 0x%x' % (name, f))
out.write_text('\n'.join(lines) + '\n')
print(out, len(seen), 'distinct Serialize functions')
